### ISSUE TITLE
Status_code for solar charging

### ISSUE THREAD

**Issue by leeyuentuen** [egnerfl/alfen_wallbox#11]
I think there are extra status code when I use the latest firmware (6.xxx)
I've add 41,42,43, but there is also sometimes 35
Should be related with solar charging 

Not 100% sure about the description

```
    def status_as_str(self):
        switcher = {
            4: "Available",
            7: "Cable connected",
            10: "Vehicle connected",
            11: "Charging",
            17: "Session end", #(Unit with socket only?) Cable still connected to EVSE after charging, but car disconnected. Screen shows charging stats until cable disconnected from EVSE.
            34: "Blocked", #EVSE is blocked through management interface of CPO.
 	    36: "Paused",
	    38: "Charging Prepare",
	    39: "Solar Charging Wait",
            41: "Solar Charging Full",
            42: "Charger Ready, Wait for charging",
 	    43: "Solar Charging Partial"
        }
```

**Comment by leeyuentuen** [comment]
fix on this MR: https://github.com/egnerfl/alfen_wallbox/pull/13

**Comment by trinneberg** [comment]
I found this issue while searching for an explanation of the status codes. But looks like the list above is not complete. When I stopped charging and restartet it, I got the sequence 11, 16, 17, 9, 11. What are 16 and 9? Could the list be added to the documentation too?

**Comment by leeyuentuen** [comment]
they are visible in my fork version:

https://github.com/leeyuentuen/alfen_wallbox/blob/e675f8b46de50aa58ae54560fc6051afd829d50a/custom_components/alfen_wallbox/sensor.py#L85
