### ISSUE TITLE
No longer on HACS?

### ISSUE THREAD

**Issue by Gotanius** [egnerfl/alfen_wallbox#17]
I can't seem to find the integration on HACS. 
Garo is still there, but this one isn't.

**Comment by Dewinn23** [comment]
Same issue here

**Comment by Carsten614** [comment]
Same here

**Comment by Carsten614** [comment]
Found it under "Egner"

**Comment by Dewinn23** [comment]
Me neither. Verstuurd vanaf mijn iPhoneOp 11 jul. 2023 om 19:40 heeft Gotanius ***@***.***> het volgende geschreven:﻿
I can't find it under "Egner".

**Comment by Carsten614** [comment]
Sorry guys, it was different. I loaded manually it from Github and then I could find it in the repository. But I think the key is to click on the three dots on the top right, add the repository and paste the Github link.

**Comment by Dewinn23** [comment]
> Sorry guys, it was different. I loaded manually it from Github and then I could find it in the repository. But I think the key is to click on the three dots on the top right, add the repository and paste the Github link. 

That did the trick. Thanks!

**Comment by leeyuentuen** [comment]
maybe this is an interesting repo?

https://github.com/leeyuentuen/alfen_wallbox
