### ISSUE TITLE
Integration blocking Logins and Backoffice integration

### ISSUE THREAD

**Issue by menloperk** [egnerfl/alfen_wallbox#18]
I have used this integration for a couple of weeks now and I like it. However, it seems to sort of block other ways of communicating with the Charge Point. When I login to ACE Service Installer, the 2nd login ('Owner') is always troublesome. When I try to login, it says the Charge Point can't be reached where in fact nothing is wrong with it. When I disable the integration it is as normal and I see no issues. Now I got an email from my Backoffice provider saying the Charge Point is not reachable. I guess the same issue is bothering here. I have the integration disabled now but what can be configured to see if we can get around this, if at all??

**Comment by egnerfl** [comment]
Hi @menloperk, a quick fix might be to increase the `MIN_TIME_BETWEEN_UPDATES` in https://github.com/egnerfl/alfen_wallbox/blob/master/custom_components/alfen_wallbox/alfen.py#L17C1-L17C25

This can be done by updating the file in your custom components dir on you local install and restarting Home Assistant.

If this fixes the issue I could add a config parameter to the integration. I would suggest a value between 120 - 600, currently it's 30 seconds to the chance of kicking out the back office is quite hight.

@leeyuentuen might has a cleaner solution in place, his fork of the integration has much more features so this might even be included already?

**Comment by menloperk** [comment]
Thanks, that's what I assumed. I disabled the integration to be able to login through ACE Service Installer. That was needed to control some of the setting that could not be done through this integration. It was annoying to do this every time. However, with the new fork that I wasn't aware of, it seems I can now control all through HA which is really awesome!!!
