### ISSUE TITLE
Add sensors and service to switch 1-phase and 3-phase charging

### ISSUE THREAD

**Issue by Emacee** [egnerfl/alfen_wallbox#6]
Hi, 

I'm trying to add some sensor to this custom components to be able to track the status of the charging station. 

I would like to see the following sensor that I used to read from the charging station;

- mainActiveLoadBalancingMaxCurrent
- meter1_frequency
- sysActiveLoadBalancingSafeCurrent

I can see the API ID's in the following code:
https://gitlab.com/LordGaav/alfen-eve/-/blob/develop/alfeneve/alfen.py

However the formatting is different than the ID's used in this custom component. 
Any clues on how to determine what the right ID should be so I can try to add these sensor to the code of this component? 
Is there any API documentation availble? Would be nice to be able to switch between 1-phase and 3-phase charging through this integration as well.

**Comment by Dominic-070** [comment]
That would be absolutely great.

**Comment by Yocairo** [comment]
As long as 2185_0 (enable phase switching is enabled), this could work by setting 2189_0 (max allowed phases) to either 1 (single phase charging) or 3 (triple phase charging). Not sure if you need the 6.3.x firmware version for this, might work with older versions as well.

**Comment by Yocairo** [comment]
As long as 2185_0 (enable phase switching is enabled), this could work by setting 2189_0 (max allowed phases) to either 1 (single phase charging) or 3 (triple phase charging). Not sure if you need the 6.3.x firmware version for this, might work with older versions as well.

**Comment by lohralfen** [comment]
As long as 2185_0 (enable phase switching is enabled), this could work by setting 2189_0 (max allowed phases) to either 1 (single phase charging) or 3 (triple phase charging). Not sure if you need the 6.3.x firmware version for this, might work with older versions as well.

**Comment by leeyuentuen** [comment]
enable and disable phase switching is possible on the MR
also the following value is included

- mainActiveLoadBalancingMaxCurrent
- sysActiveLoadBalancingSafeCurrent

**Comment by mahil4711** [comment]
Have done some manual testing concerning the phase switching on a box with firmware 5.8.1-4123. Allthough 2185_0 (enable phase switching) is 0 (disabled), I was able to set 2189_0 (max allowed phases) to either 1 or 3. But this needs to be set before the charging process starts. Changing this value afterwards has no effect on a running charging process.

**Comment by lohralfen** [comment]
> Have done some manual testing concerning the phase switching on a box with firmware 5.8.1-4123. Allthough 2185_0 (enable phase switching) is 0 (disabled), I was able to set 2189_0 (max allowed phases) to either 1 or 3. But this needs to be set before the charging process starts. Changing this value afterwards has no effect on a running charging process.

You're not using the latest firmware, but regardless of that I'm not sure if latest firmware already supports to change this during charging session. Version 6.5.0 will support this, though. Currently it's only via OCPP ChargingProfiles that phases can be switched during the session, I think.

**Comment by mahil4711** [comment]
@lohralfen: A bit off topic, but do you know of any possiblity to start a charging session over this API? Background: I have 2 different RFID cards, with which I start normally the charging session, after the cable was plugged. Both are billed differently. So is there a way to use to API to do that?

**Comment by Dominic-070** [comment]
Check this fork https://github.com/leeyuentuen/alfen_wallbox
